# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=200)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('balance_acc', models.FloatField(default=0)),
                ('dtlast_upd', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('tel_no', models.CharField(max_length=50)),
                ('allow_ar', models.BooleanField(default=False)),
                ('bad_acc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_desc', models.CharField(max_length=50)),
                ('service_fee', models.FloatField(default=0)),
                ('service_time', models.FloatField(default=0)),
                ('service_uom', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='JobOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_qty', models.FloatField(default=0)),
                ('service_fee', models.FloatField(default=0)),
                ('fkid_job', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Job')),
            ],
        ),
        migrations.CreateModel(
            name='JobOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateTimeField(blank=True, null=True)),
                ('target_date', models.DateTimeField(blank=True, null=True)),
                ('stat', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=200)),
                ('balance_acc', models.FloatField(default=0)),
                ('dtlast_updated', models.DateTimeField(blank=True, null=True)),
                ('id_user', models.IntegerField(default=0)),
                ('fkid_cust', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='JobPartUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('srp', models.FloatField(default=0)),
                ('unit_cost', models.FloatField(default=0)),
                ('balance_qty', models.FloatField(default=0)),
                ('balance_cost', models.FloatField(default=0)),
                ('fkid_jobOrder', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.JobOrders')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=20)),
                ('part_desc', models.CharField(max_length=50)),
                ('srp', models.FloatField(default=0)),
                ('latest_rr', models.CharField(max_length=45)),
                ('latest_rr_date', models.DateField(blank=True, null=True)),
                ('latest_supplier', models.IntegerField(default=0)),
                ('uom', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PartsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=12)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('dtlast_updated', models.DateTimeField(blank=True, null=True)),
                ('id_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartsOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('unit_cost', models.FloatField(default=0)),
                ('balance_qty', models.FloatField(default=0)),
                ('balance_cost', models.FloatField(default=0)),
                ('fkid_parts', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Parts')),
            ],
        ),
        migrations.CreateModel(
            name='PartsReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_dt', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('balance_acc', models.FloatField(default=0)),
                ('fkid_partsOrder', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.PartsOrder')),
            ],
        ),
        migrations.CreateModel(
            name='PartsRecievedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parts', models.IntegerField(null=True)),
                ('qty', models.FloatField(default=0)),
                ('unit_cost', models.FloatField(default=0)),
                ('balance_qty', models.FloatField(default=0)),
                ('balance_cost', models.FloatField(default=0)),
                ('dtlast_upd', models.DateTimeField(blank=True, null=True)),
                ('id_user', models.IntegerField(default=0)),
                ('fkidParts_received', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.PartsReceived')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_dt', models.DateField(blank=True, null=True)),
                ('id_supplier', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('balance_acc', models.FloatField(default=0)),
                ('dtLast_upd', models.DateField(blank=True, null=True)),
                ('id_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('fkidParts_received', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.PartsReceived')),
                ('fkid_payment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Payments')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('tel_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('mid_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('spec_area', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=15)),
                ('make', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('engine_no', models.CharField(max_length=50)),
                ('chasis_no', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=15)),
                ('fkid_cust', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='partsreceived',
            name='fkid_supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Supplier'),
        ),
        migrations.AddField(
            model_name='partsorder',
            name='fkid_supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Supplier'),
        ),
        migrations.AddField(
            model_name='jobpartusage',
            name='fkid_parts',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Parts'),
        ),
        migrations.AddField(
            model_name='joborders',
            name='fkplate_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Vehicle'),
        ),
        migrations.AddField(
            model_name='joborderdetail',
            name='fkid_jobOrder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.JobOrders'),
        ),
        migrations.AddField(
            model_name='joborderdetail',
            name='fkid_technician',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Technician'),
        ),
        migrations.AddField(
            model_name='job',
            name='fkid_jobType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.JobType'),
        ),
        migrations.AddField(
            model_name='collections',
            name='fkid_cust',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Customer'),
        ),
        migrations.AddField(
            model_name='collectiondetail',
            name='fkid_collections',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Collections'),
        ),
        migrations.AddField(
            model_name='collectiondetail',
            name='fkid_jobOrders',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.JobOrders'),
        ),
    ]
