# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='latest_supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Supplier'),
        ),
    ]
