# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170716_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_no',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
